### ISSUE TITLE
Error when calling `.map` on an undefined object

### ISSUE THREAD

**Issue by ashryanbeats** [astoria-tech/volunteer-dispatch#19]
In `index.js`, we have this line:

`const tasks = request.get('Tasks').map(Task.mapFromRawTask) || [];`

If the user hasn't entered any primary tasks (items in the "Tasks" field of the form), that `.map` call will error out and prevent the record in Airtable from being processed. This is because it's calling `.map` on `undefined`.

Since we have a "Tasks - Other" field, presumably it's conceivable that a user would skip the primary tasks and manually enter one in the "Tasks - Other" field.

I can take this one, but don't want to mess up anything in the code's Airtable land if it's still in flux.

https://github.com/astoria-tech/volunteer-dispatch/blob/0af64dc593dac63aae5380fa413dfa7a382b4374/src/index.js#L30

**Comment by James-Quigley** [comment]
I'll take this one.
