### ISSUE TITLE
Empty duplicate of airtable base

### ISSUE THREAD

**Issue by tysonvinson** [astoria-tech/volunteer-dispatch#2]
Hi,
I'm working on some similar mutual aid efforts in Colorado. Someone from the group may have already reached out regarding this, but I was wondering if you could duplicate the airtable you're using so that I can test drive this node app. I think this is a useful workflow and we can contribute back to this app if we're both working off the same schema.

**Comment by azlyth** [comment]
Hey @tysonvinson, sorry for the delay in response, I hadn't seen this issue here.

Our README now has a link to a template of our Airtable base, which you can copy with one click! The only thing left would be to procure those API keys.

**Comment by azlyth** [comment]
Let us know if you have any further questions!
