### ISSUE TITLE
bot.chat.postMessage will fail if message is longer than 3001 characters

### ISSUE THREAD

**Issue by ashryanbeats** [astoria-tech/volunteer-dispatch#20]
If #18 is merged, it adds support for the "Anything else?" field. If a user really types a lot in that field and causes the total character count of the message passed to `bot.chat.postMessage` to go over 3001 characters, the API call will fail.

If we want to be safe, we should check character count of the entire message before making that call. If the char count is > 3001, we can substitute the `anythingElse` block content with "See Airtable for further notes from the requester", or something along those lines.

**Comment by James-Quigley** [comment]
From [Slack's Docs](https://api.slack.com/methods/chat.postMessage):
> For best results, limit the number of characters in the text field to 4,000 characters. Ideally, messages should be short and human-readable. Slack will truncate messages containing more than 40,000 characters.

If you need to post longer messages, please consider uploading a snippet instead.

**Comment by ashryanbeats** [comment]
Interesting! Doesn’t seem to jibe with the reproducible error message their API was throwing at me last night. 

To reproduce, you can just throw 4-5 paragraphs of Lorem ipsum in the “Anything else” field. 

Perhaps it’s a limitation from the Slack node module?

Shouldn’t be too hard to dig into. Just need to make the time if we feel like this is a likely scenario a user could hit.

**Comment by James-Quigley** [comment]
Yeah node module might be different. Slack recommends truncating the message on our end well before that character limit. Or we could split it up into different messages.
